apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: ised-nginx-s2i
    application: ised-nginx
    template: ised-nginx-s2i
  name: ised-nginxl
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: ised-nginx:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: "andrew-test"
      uri: https://github.com/ised-isde-canada/ised-nginx-s2i.git
    type: Git
  strategy:
    sourceStrategy:
      forcePull: true
      from:
        kind: ImageStreamTag
        name: nginx:1.12
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
