kind: Template
apiVersion: v1
labels:
  template: ised-nginx-non-prod-template
message: |-
  The following items have been created in your project:

                Service: ised-nginx
                 Routes: dev.ised-isde.canada.ca
                         intranet-dev.ised-isde.canada.ca
                         uat.ised-isde.canada.ca
                         intranet-uat.ised-isde.canada.ca
                         qa.ised-isde.canada.ca
                         intranet-qa.ised-isde.canada.ca
metadata:
  name: ised-nginx-non-prod-template
  annotations:
    openshift.io/display-name: "ISED NGiNX Proxy - Non-PROD"
    description: >-
      Reverse proxy for Non-PROD OpenShift apps, as well as redirect epic (/eic and /utils) resources.
    iconClass: icon-nginx
    tags: "nginx,proxy,ised"
    openshift.io/provider-display-name: "ISED Canada"
    openshift.io/documentation-url: "https://github.com/ised-isde-canada/ised-nginx-s2i"
objects:
# NGiNX
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations: null
    labels:
      app: ised-nginx-non-prod
    name: ised-nginx-non-prod
  spec:
    replicas: 1
    selector:
      app: ised-nginx-non-prod
      deploymentconfig: ised-nginx-non-prod
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ised-nginx-non-prod
          deploymentconfig: ised-nginx-non-prod
      spec:
        containers:
        - env:
          - name: ENVIRONMENT
            value: "non-prod"
          imagePullPolicy: Always
          name: ised-nginx
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              memory: 128Mi
            requests:
              cpu: 100m
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: "/eic/site/080.nsf/eng/home"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 3
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/eic/site/080.nsf/eng/home"
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ised-nginx
        from:
          kind: ImageStreamTag
          name: ised-nginx:non-prod
          namespace: ised-ci
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations: null
    creationTimestamp: null
    labels:
      app: ised-nginx-non-prod
    name: ised-nginx-non-prod
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: ised-nginx-non-prod
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
# Routes.
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/ip_whitelist: 192.197.178.2/32
    labels:
      app: ised-nginx-non-prod
      domain: ised
    name: ised-nginx-dev
  spec:
    host: "dev.ised-isde.canada.ca"
    path: "/"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ised-nginx-non-prod
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/ip_whitelist: 192.197.178.2/32
    labels:
      app: ised-nginx-non-prod
      domain: ised
    name: ised-nginx-intranet-dev
  spec:
    host: "intranet-dev.ised-isde.canada.ca"
    path: "/"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ised-nginx-non-prod
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/ip_whitelist: 192.197.178.2/32
    labels:
      app: ised-nginx-non-prod
      domain: ised
    name: ised-nginx-uat
  spec:
    host: "uat.ised-isde.canada.ca"
    path: "/"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ised-nginx-non-prod
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/ip_whitelist: 192.197.178.2/32
    labels:
      app: ised-nginx-non-prod
      domain: ised
    name: ised-nginx-intranet-uat
  spec:
    host: "intranet-uat.ised-isde.canada.ca"
    path: "/"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ised-nginx-non-prod
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/ip_whitelist: 192.197.178.2/32
    labels:
      app: ised-nginx-non-prod
      domain: ised
    name: ised-nginx-qa
  spec:
    host: "qa.ised-isde.canada.ca"
    path: "/"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ised-nginx-non-prod
- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      haproxy.router.openshift.io/ip_whitelist: 192.197.178.2/32
    labels:
      app: ised-nginx-non-prod
      domain: ised
    name: ised-nginx-intranet-qa
  spec:
    host: "intranet-qa.ised-isde.canada.ca"
    path: "/"
    port:
      targetPort: 8080-tcp
    to:
      kind: Service
      name: ised-nginx-non-prod
